name: on_push

on:
  push:
    branch:
      - "**"

jobs:

    build_exec_test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: 18
        - name: Cache local Maven repository
          uses: actions/cache@v2
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - name: Run RestAssured tests using Maven
          run: mvn test
        - name: Generate Reports
          if: ${{ always() }}
          run: mvn allure:report
        - name: Store Reports
          uses: actions/upload-artifact@v3
            with:
              name: allure-reports
              path: target/site/allure-maven-plugin